#ifndef _GENERAL_H_
#define _GENERAL_H_

#define GLOBAL_TIMESTEP_NS              100

#define LOWPASS_FILTER_RES_1_VALUE      100
#define LOWPASS_FILTER_CAP_1_VALUE      0.00000002

#define SQUARE_WAVE_FREQUNECY_KHZ       100
#define SQUARE_WAVE_PERIOD_US           (1000 / SQUARE_WAVE_FREQUNECY_KHZ)
#define SQUARE_WAVE_MAX_VALUE           5
#define SQUARE_WAVE_MIN_VALUE           -5

#define ADC_MAXIMUM_VALUE               1000
#define ADC_OUTPUT_BITS                 16

#define REGISTER_LOGIC_Z_VALUE          "ZZZZZZZZZZZZZZZZ"
#define REGISTER_CLOCK_FREQUENCY_MHZ    1

#define TIMER_TIMEOUT_INTERVAL_MS       1
#define TIMER_TIMEOUT_INTERVAL_US       (TIMER_TIMEOUT_INTERVAL_MS * 1000)
#define TIMER_BASE_ADDRESS              0xF018
#define TIMER_TIMEOUT_SET_VALUE         "0000000000000001"
#define TIMER_TIMEOUT_CLEAR_VALUE       "0000000000000000"
#define TIMER_TIMEOUT_Z_VALUE           "ZZZZZZZZZZZZZZZZ"

#define SENSOR_BASE_ADDRESS             0xF010
#define BUS_ADDRESS_IO_MASK             0xF0FF

#endif